[package]
name = "openvb_dart_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
openvb = { git = "ssh://git@github.com/ExpressiveLabs/openvb-rs.git" }
serde = "1.0.215"
serde_json = "1.0.133"

[lib]
crate-type = ["cdylib"]
